"""Steps 3 and 6: save AI-drafted follow-up emails and document checklists.

Review banners are added here, in code, so no draft can reach a client or an attorney without
being clearly labeled, whatever the model wrote.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path

from .models import IntakeExtraction

_RULE = "=" * 72


def save_followup(
    folder: Path, source_file: str, record: IntakeExtraction, draft: str, generator: str
) -> Path:
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / f"{Path(source_file).stem}_followup.txt"
    header = "\n".join(
        [
            _RULE,
            "DRAFT - NOT SENT. Intake staff must review and approve before sending.",
            _RULE,
            f"Source email:   {source_file}",
            f"Missing fields: {', '.join(record.missing_field_labels)}",
            f"To:             {record.email or 'UNKNOWN - reply to the original message'}",
            f"Drafted by:     {generator}",
            f"Drafted at:     {datetime.now():%Y-%m-%d %H:%M}",
            "-" * 72,
        ]
    )
    path.write_text(f"{header}\n\n{draft.strip()}\n", encoding="utf-8")
    return path


def save_checklist(folder: Path, case_id: str, record: IntakeExtraction, draft: str, generator: str) -> Path:
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / f"{case_id}.md"
    content = f"""# Document checklist: {record.case_type.value}

> **DRAFT FOR ATTORNEY REVIEW. NOT LEGAL ADVICE.**
> Generated automatically as a starting point. An attorney must review and adapt it before
> anything is shared with the client.

- **Case ID:** {case_id}
- **Case type:** {record.case_type.value}
- **Country of citizenship:** {record.country_of_citizenship or "not stated"}
- **Generated by:** {generator}
- **Generated at:** {datetime.now():%Y-%m-%d %H:%M}

{draft.strip()}

---
*Draft for attorney review. Not legal advice. Requirements change; verify against current
official instructions before relying on this list.*
"""
    path.write_text(content, encoding="utf-8")
    return path


@dataclass(frozen=True)
class ReviewTicket:
    source_file: str
    attempts: int
    errors: list[str]
    raw_outputs: list[str]


def save_review_ticket(folder: Path, ticket: ReviewTicket) -> Path:
    """Record why extraction failed so a person can finish the intake by hand."""
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / f"{Path(ticket.source_file).stem}.json"
    path.write_text(json.dumps(asdict(ticket), indent=2) + "\n", encoding="utf-8")
    return path
